CommonService
GameObject CommonService.FindNearestEnemy(GameObject me)
References IsAlive, IsEnemy.
bool CommonService.IsEnemy(GameObject me, Collider2D unit)
Referenced by FindNearestEnemy.
bool CommonService.IsEnemy(GameObject me, GameObject otherGameObject)
void CommonService.MakeDead(GameObject gameObject)
References Dead.
GameObject CommonService.FindNearestResource(GameObject me)
References ResourceHandler.GetPreferedResourceType, IsAnyResource.
bool CommonService.IsAlive(GameObject target)
References Dead, Destroyed, BugStateHandler.GetState.
Referenced by FindNearestEnemy.
bool CommonService.IsAnyResource(GameObject targetResource)
References Resource.GetTotalResourceAmmount.
Referenced by FindNearestResource.