AiBreeder
List<GameObject> AiBreeder.bugPrefabs
Referenced by Breed.
List<int> AiBreeder.playerWeights
Referenced by Breed.
int AiBreeder.maxSteps
Referenced by Update.
int AiBreeder.maxN
Referenced by Breed, GetMaxN.
int AiBreeder.maxM
Referenced by Breed, GetMaxM.
int AiBreeder.randomRange
Referenced by Breed.
int AiBreeder.currentStep
Referenced by Update.
int AiBreeder.currentBreed
Referenced by Breed, GetCurrentBreed.
BugTypeEnum [] AiBreeder.bugTypes
Referenced by Start.
void AiBreeder.Awake()
void AiBreeder.Start()
References bugTypes.
void AiBreeder.Update()
References Breed, currentStep, maxSteps.
void AiBreeder.BreedOne(GameObject gameObject, int playerIndex, int deltaN, int deltaM)
Referenced by Breed.
void AiBreeder.Clear()
Referenced by Breed.
int AiBreeder.GetMaxN()
References maxN.
int AiBreeder.GetMaxM()
References maxM.
int AiBreeder.GetPlayersNum()
int AiBreeder.GetCurrentBreed()
References currentBreed.
void AiBreeder.Breed()
References Clear, currentBreed, maxM, maxN, playerWeights, randomRange.
Referenced by Update.
void AiBreeder.Breed(int playerIndex, int playerWeight, int deltaN, int deltaM)
References BreedOne, bugPrefabs.