BugActionSet
GameObject BugActionSet.nearestEnemy
Referenced by FindNearestEnemy.
GameObject BugActionSet.nearestResource
Referenced by FindNearestResource.
void BugActionSet.Start()
void BugActionSet.Update()
void BugActionSet.RunAway(GameObject nearestEnemy)
References BaseRunAway.
void BugActionSet.RunAway(Vector3 directionVector)
References BaseRunAway.
GameObject BugActionSet.FindNearestEnemy()
References nearestEnemy.
GameObject BugActionSet.FindNearestResource()
References nearestResource.
bool BugActionSet.IsEnemy(GameObject otherGameObject)
bool BugActionSet.IsAnyResource(GameObject targetResource)
Referenced by MoveToHarvest.
void BugActionSet.Attacked()
void BugActionSet.Dead()
void BugActionSet.Idle()
Referenced by MoveToAttack, MoveToCastle, MoveToHarvest.
void BugActionSet.Attack(GameObject localTargetToAttack=null)
void BugActionSet.UnloadResourceToCastle(GameObject castle)
void BugActionSet.MoveToHarvest(GameObject targetToHarcest)
References Idle, IsAnyResource, Move.
void BugActionSet.MoveToAttack(GameObject targetToAttack)
References Idle, Move.
void BugActionSet.MoveToCastle(GameObject castle)
References Idle, Move.
void BugActionSet.BaseRunAway(Vector2 target)
References Move.
Referenced by RunAway.
void BugActionSet.Move(Vector2 target)
Referenced by BaseRunAway, MoveToAttack, MoveToCastle, MoveToHarvest.
void BugActionSet.Harvest()