BugStateHandler
BugStateEnum BugStateHandler.state
Referenced by GetState, HandleStates, InitState, SetState.
bool BugStateHandler.decideAttack
Referenced by SetDecideAttack.
GameObject BugStateHandler.targetToAttack
Referenced by HandleStates, SetNoAttackTarget, SetTargetToAttack.
GameObject BugStateHandler.targetToHarvest
Referenced by HandleStates, SetNoTargetToHarvest, SetTargetToHarvest.
GameObject BugStateHandler.targetCastle
Referenced by HandleStates, SetTargetCastle.
float BugStateHandler.carriedResource
bool BugStateHandler.requested
Referenced by SetDecideAttack.
BugStateEnum BugStateHandler.GetState()
References state.
Referenced by Horde.CheckIfFinished, Horde.FindNearestEnemy, HandleStates, CommonService.IsAlive.
void BugStateHandler.InitState(BugStateEnum value)
References Idle, state.
void BugStateHandler.SetState(BugStateEnum value)
References state.
Referenced by HandleStates.
void BugStateHandler.SetDecideAttack(bool decideAttack)
References decideAttack, requested.
void BugStateHandler.SetNoAttackTarget(GameObject targetToDelete)
References Bug.GetId, targetToAttack.
void BugStateHandler.SetTargetToAttack(GameObject targetToAttack)
References targetToAttack.
void BugStateHandler.SetNoTargetToHarvest(GameObject targetToDelete)
References targetToHarvest.
void BugStateHandler.SetTargetToHarvest(GameObject targetToHarvest)
References targetToHarvest.
void BugStateHandler.HandleStates()
References Attack, GetState, Harvest, Idle, Move, MoveToAttack, MoveToHarvest, SetState, state, targetCastle, targetToAttack, targetToHarvest.
void BugStateHandler.SetTargetCastle(GameObject birthCastle)
References targetCastle.