Bug
int Bug.current
Referenced by Update.
int Bug.bugId
Referenced by Awake, GetId.
ResourceTypeEnum Bug.bugCreationResoucreType
Referenced by GetBugCreationResoucreType.
float Bug.bugCreationResourceAmmount
Referenced by GetBugCreationResourceAmmount.
float Bug.bugCreationTime
Referenced by GetBugCreationTime.
GameObject Bug.birthCastle
Referenced by GetBirthCastle.
int Bug._nextId
int Bug.NextId
Referenced by Awake.
void Bug.Awake()
References bugId, NextId.
void Bug.Start()
void Bug.Update()
References current.
int Bug.GetId()
References bugId.
Referenced by Horde.Add, EntityCollection.AddBug, AiEntityCollection.AddBug, Horde.Lookup, BugStateHandler.SetNoAttackTarget.
ResourceTypeEnum Bug.GetBugCreationResoucreType()
References bugCreationResoucreType.
float Bug.GetBugCreationResourceAmmount()
References bugCreationResourceAmmount.
float Bug.GetBugCreationTime()
References bugCreationTime.
GameObject Bug.GetBirthCastle()
References birthCastle.