AiEntityCollection
int AiEntityCollection.calculateHordesFrame
int AiEntityCollection.maxHordesNumber
Referenced by Start.
Horde AiEntityCollection.hordePrefab
Referenced by CreateHordePool.
List<NNModel> AiEntityCollection.models
ConcurrentDictionary<int,GameObject> AiEntityCollection._bugs
Referenced by AddBug, Awake, CalculateHordes, ClearBugs, RemoveBug.
Dictionary<string, List<HordePoolObject> > AiEntityCollection._hordePool
Referenced by Awake, AwardHordePool, EndHordePoolEpisode, GetHorde, ResetHordePool, Start.
List<Horde> AiEntityCollection._hordes
Referenced by Awake, CalculateHordes, ClearHordes.
void AiEntityCollection.Awake()
References _bugs, _hordePool, _hordes.
void AiEntityCollection.Start()
References _hordePool, CreateHordePool, maxHordesNumber.
Dictionary<string, List<HordePoolObject> > AiEntityCollection.CreateHordePool(int v)
References hordePrefab.
Referenced by Start.
Horde AiEntityCollection.GetHorde(string teamId)
References _hordePool.
Referenced by CalculateHordes, GetMyHorde.
void AiEntityCollection.AwardHordePool()
References _hordePool.
void AiEntityCollection.ClearHordes()
References _hordes.
void AiEntityCollection.ResetHordePool()
References _hordePool.
void AiEntityCollection.EndHordePoolEpisode()
References _hordePool.
void AiEntityCollection.AddBug(GameObject bug)
References _bugs, Bug.GetId.
int AiEntityCollection.GetTeamWeight(GameObject bug)
void AiEntityCollection.RemoveBug(GameObject bug)
References _bugs.
Referenced by ClearBugs.
void AiEntityCollection.ClearBugs()
References _bugs, RemoveBug.
Horde AiEntityCollection.GetMyHorde(GameObject bug)
References GetHorde.
void AiEntityCollection.CalculateHordes()
References _bugs, _hordes, GetHorde.