CastleStateHandler
CastleTypeEnum CastleStateHandler.castleType
CastleStateEnum CastleStateHandler.castleState
Referenced by CreateBug, GetState, HandleCastleState, SetState, Update.
CastleJobEnum CastleStateHandler.castleJob
Referenced by DoCastleJob, Start.
float [] CastleStateHandler.ownedResourceAmmount
Referenced by AddResource, HasEnoughResource, InitializeResourceAmmount, TakeResourceForCreation.
ResourceTypeEnum CastleStateHandler.preferedResourceType
Referenced by InitializeResourceAmmount.
float CastleStateHandler.startValueOfPreferedResourceType
Referenced by InitializeResourceAmmount.
BugTypeEnum [] CastleStateHandler.bugCreationQueue
Referenced by AddNewBugToQueue, CreateBug, IsAnyBugInQueue, SetNewCreationUnit, ShiftQueue, Start.
GameObject [] CastleStateHandler.bugPrefabs
Referenced by CreateBug, GetCreationTimeOfBug, HasEnoughResource, TakeResourceForCreation.
BugTypeEnum [] CastleStateHandler.bugPrefabKeys
Referenced by CreateBug, Start.
GameObject CastleStateHandler.targetToAttack
Referenced by FindAttacker.
const int CastleStateHandler.bugPrefabCount
float CastleStateHandler.bugCreationPeriod
Referenced by CreateUnit.
float CastleStateHandler.bugCreationTimeLeft
Referenced by CreateUnit, SetNewCreationUnit, Start.
System.DateTime CastleStateHandler.start
Referenced by Start, Update.
int CastleStateHandler.healthIncreasingValue
Referenced by IncreaseHealth.
float CastleStateHandler.defaultScale
Referenced by Update.
void CastleStateHandler.Start()
References AddNewBugToQueue, bugCreationQueue, bugCreationTimeLeft, bugPrefabKeys, castleJob, CreatingUnit, GetCreationTimeOfBug, InitializeResourceAmmount, start.
void CastleStateHandler.AddNewBugToQueue(BugTypeEnum bugTypeEnum)
References bugCreationQueue.
Referenced by Start.
List<ResourceTypeEnum> CastleStateHandler.GetResourceTypes()
Referenced by AddResource, HasEnoughResource, InitializeResourceAmmount, TakeResourceForCreation.
void CastleStateHandler.InitializeResourceAmmount()
References GetResourceTypes, ownedResourceAmmount, preferedResourceType, startValueOfPreferedResourceType.
Referenced by Start.
void CastleStateHandler.Update()
References castleState, defaultScale, Destroyed, DoCastleJob, HandleCastleState, start.
void CastleStateHandler.SetState(CastleStateEnum mewCastleState)
References castleState.
Referenced by FindAttacker.
void CastleStateHandler.HandleCastleState()
References Attack, castleState, Destroyed, FindAttacker, Health.GetHealth.
Referenced by Update.
void CastleStateHandler.Attack()
Referenced by HandleCastleState.
void CastleStateHandler.FindAttacker()
References SetState, targetToAttack.
Referenced by HandleCastleState.
void CastleStateHandler.DoCastleJob()
References castleJob, CreateUnit, IncreaseHealth, IsAnyBugInQueue.
Referenced by Update.
bool CastleStateHandler.IsAnyBugInQueue()
References bugCreationQueue.
Referenced by DoCastleJob.
void CastleStateHandler.IncreaseHealth()
References healthIncreasingValue.
Referenced by DoCastleJob.
void CastleStateHandler.CreateUnit()
References bugCreationPeriod, bugCreationTimeLeft, CreateBug, SetNewCreationUnit.
Referenced by DoCastleJob.
void CastleStateHandler.SetNewCreationUnit()
References bugCreationQueue, bugCreationTimeLeft, GetCreationTimeOfBug, HasEnoughResource, TakeResourceForCreation.
Referenced by CreateUnit.
void CastleStateHandler.TakeResourceForCreation(BugTypeEnum bugType)
References bugPrefabs, GetResourceTypes, ownedResourceAmmount.
Referenced by SetNewCreationUnit.
bool CastleStateHandler.HasEnoughResource(BugTypeEnum bugType)
References bugPrefabs, GetResourceTypes, ownedResourceAmmount.
Referenced by SetNewCreationUnit.
float CastleStateHandler.GetCreationTimeOfBug(BugTypeEnum bugType)
References bugPrefabs.
Referenced by SetNewCreationUnit, Start.
void CastleStateHandler.CreateBug()
References bugCreationQueue, ShiftQueue.
Referenced by CreateUnit.
void CastleStateHandler.ShiftQueue()
References bugCreationQueue.
Referenced by CreateBug.
GameObject CastleStateHandler.CreateBug(BugTypeEnum bugType)
References bugPrefabKeys, bugPrefabs, castleState.
void CastleStateHandler.AddResource(ResourceTypeEnum resourceType, float ammount)
References GetResourceTypes, ownedResourceAmmount.
CastleStateEnum CastleStateHandler.GetState()
References castleState.