EntityCollection
int EntityCollection.calculateHordesFrame
int EntityCollection.maxHordesNumber
Horde EntityCollection.hordePrefab
Referenced by CreateHordePool.
List<NNModel> EntityCollection.models
ConcurrentDictionary<int,GameObject> EntityCollection._bugs
Referenced by AddBug, Awake, CalculateHordes, ClearBugs, RemoveBug.
Dictionary<string, List<HordePoolObject> > EntityCollection._hordePool
Referenced by Awake, AwardHordePool, EndHordePoolEpisode, GetHorde, ResetHordePool.
List<Horde> EntityCollection._hordes
Referenced by Awake, CalculateHordes, ClearHordes.
void EntityCollection.Awake()
References _bugs, _hordePool, _hordes, CreateHordePool.
void EntityCollection.Start()
Dictionary<string, List<HordePoolObject> > EntityCollection.CreateHordePool(int v)
References hordePrefab.
Referenced by Awake.
Horde EntityCollection.GetHorde(string teamId)
References _hordePool.
Referenced by CalculateHordes, GetMyHorde.
void EntityCollection.AwardHordePool()
References _hordePool.
void EntityCollection.ClearHordes()
References _hordes.
void EntityCollection.ResetHordePool()
References _hordePool.
void EntityCollection.EndHordePoolEpisode()
References _hordePool.
void EntityCollection.AddBug(GameObject bug)
References _bugs, Bug.GetId.
int EntityCollection.GetTeamWeight(GameObject bug)
void EntityCollection.RemoveBug(GameObject bug)
References _bugs.
Referenced by ClearBugs.
void EntityCollection.ClearBugs()
References _bugs, RemoveBug.
Horde EntityCollection.GetMyHorde(GameObject bug)
References GetHorde.
void EntityCollection.CalculateHordes()
References _bugs, _hordes, GetHorde.