Horde
int Horde.counter
Referenced by Initialize.
ConcurrentDictionary<int, HordeMember> Horde._members
Referenced by Add, ContainsBug, FindHordeCenter, GetAliveSum, GetNearestEnemy, GetWeightSum, Lookup, Members, Remove.
List<BugTypeEnum> Horde._species
Referenced by GetCumulativeWeight, GetWeightOfSpecies, GetZeroWeightOfSpecies, Initialize.
Horde Horde._enemyHorde
Referenced by AttackOrRunaway, AwardBeforeEndEpisode, CollectObservations, FindEnemyHorde, HandleStates, Log.
GameObject Horde._initGameObject
string Horde.myTeamId
Referenced by Log.
int Horde.teamCount
Referenced by HandleStates.
int Horde.hordeId
Referenced by Initialize.
List<float> Horde.friendsWeights
Referenced by AddObservations, CollectObservations, GetCumulativeWeights, GetWeightsAsString.
List<float> Horde.enemiesWeights
Referenced by AddObservations, CollectObservations, FindEnemyHorde, GetCumulativeWeights, GetWeightsAsString.
HordeStateEnum Horde.state
Referenced by CollectObservations, HandleStates, OnActionReceived, SetState.
bool Horde._attack
Referenced by AttackOrRunaway, AwardBeforeEndEpisode, Log, OnActionReceived.
override void Horde.Initialize()
References _species, AntFlyer, AntSlave, AntWarrior, counter, hordeId, Ladybug.
void Horde.Reset()
Referenced by OnEpisodeBegin.
void Horde.SetAgentModel(string name, NNModel model)
References Log.
override void Horde.OnEpisodeBegin()
References Reset.
override void Horde.CollectObservations(VectorSensor sensor)
References _enemyHorde, AddObservations, enemiesWeights, friendsWeights, GetWeightOfSpecies, GetZeroWeightOfSpecies, state.
override void Horde.OnActionReceived(ActionBuffers actionBuffers)
References _attack, Log, SetState, state.
BugTypeEnum Horde.GetHordeBugType()
References Members.
Referenced by Log.
bool Horde.ContainsBug(GameObject bug)
References _members.
void Horde.Remove(GameObject bug)
References _members, Log.
void Horde.Attack(Horde enemy)
References AttackEnemy, CalculateEnemyToAttack, Log, Members.
Referenced by AttackOrRunaway.
void Horde.RunAway(Horde enemy)
References FindHordeCenter, Log, Members.
Referenced by AttackOrRunaway.
GameObject Horde.GetNearestEnemy()
References _members, Enemy, FindHordeCenter, FindNearestEnemy.
void Horde.Lookup(GameObject bug, string teamId, bool root)
References _members, Add, Dead, Bug.GetId, Inserted, Log, LookedUp, Members, SetState.
List<float> Horde.GetWeightOfSpecies()
References _species, Members.
Referenced by CollectObservations.
List<float> Horde.GetZeroWeightOfSpecies()
References _species.
Referenced by CollectObservations.
float Horde.GetWeightSum()
References _members.
Referenced by AwardBeforeEndEpisode, Log, RewardAlives.
float Horde.GetAliveSum()
References _members, Dead, Members.
Referenced by AwardBeforeEndEpisode, RewardAlives.
List<GameObject> Horde.Members()
References _members, Bug.
Referenced by Attack, CheckIfFinished, FindEnemyHorde, GetAliveSum, GetHordeBugType, GetWeightOfSpecies, HandleStates, Log, Lookup, RunAway.
void Horde.AddObservations(VectorSensor sensor, List< float > friendsWeights, List< float > enemiesWeights)
References enemiesWeights, friendsWeights.
Referenced by CollectObservations.
string Horde.GetWeightsAsString()
References enemiesWeights, friendsWeights.
Referenced by Log.
string Horde.GetCumulativeWeights()
References enemiesWeights, friendsWeights, GetCumulativeWeight.
Referenced by Log.
float Horde.GetCumulativeWeight(List< float > weights)
References _species.
Referenced by GetCumulativeWeights.
void Horde.FindEnemyHorde()
References _enemyHorde, Dead, enemiesWeights, FindNearestEnemy, Members.
Referenced by HandleStates.
void Horde.Log(string temaplte)
References Members, myTeamId.
void Horde.Log()
References _attack, _enemyHorde, GetCumulativeWeights, GetHordeBugType, GetWeightsAsString, GetWeightSum.
Referenced by Add, Attack, Lookup, OnActionReceived, Remove, RunAway, SetAgentModel.
void Horde.Update()
References HandleStates, RewardAlives.
void Horde.RewardAlives()
References GetAliveSum, GetWeightSum.
Referenced by Update.
void Horde.HandleStates()
References _enemyHorde, AttackOrRunaway, CheckIfFinished, FindEnemyHorde, Members, SetState, state, teamCount.
Referenced by Update.
void Horde.SetState(HordeStateEnum newState)
References state.
Referenced by AttackOrRunaway, CheckIfFinished, HandleStates, Lookup, OnActionReceived.
void Horde.CheckIfFinished()
References All, BugStateHandler.GetState, Idle, Members, SetState.
Referenced by HandleStates.
void Horde.AttackOrRunaway()
References _attack, _enemyHorde, Attack, RunAway, SetState.
Referenced by HandleStates.
void Horde.Add(GameObject bug)
References _members, Bug.GetId, Log.
Referenced by Lookup.
GameObject Horde.FindNearestEnemy(GameObject bug)
References AreEnemies, Dead, BugStateHandler.GetState.
Referenced by FindEnemyHorde, GetNearestEnemy.
GameObject Horde.CalculateEnemyToAttack(GameObject friend, List< GameObject > enemies)
Referenced by Attack.
Vector3 Horde.FindHordeCenter()
References _members.
Referenced by GetNearestEnemy, RunAway.
void Horde.AttackEnemy(GameObject friend, GameObject enemyToAttack)
References MoveToAttack.
Referenced by Attack.
bool Horde.AreEnemies(GameObject go1, GameObject go2)
Referenced by FindNearestEnemy.
void Horde.AwardBeforeEndEpisode()
References _attack, _enemyHorde, GetAliveSum, GetWeightSum.
static List<BugTypeEnum> Horde.GetSpecies()