behaviors:
  Horde0:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 256
      learning_rate: 0.001
      beta: 0.01
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 2
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 3000
    max_steps: 100000
    time_horizon: 32
    summary_freq: 1000
    threaded: true