Unity::MLAgents::Extensions::Sensors::PoseExtractor
int [] Unity.MLAgents.Extensions.Sensors.PoseExtractor.m_ParentIndices
Pose [] Unity.MLAgents.Extensions.Sensors.PoseExtractor.m_ModelSpacePoses
Pose [] Unity.MLAgents.Extensions.Sensors.PoseExtractor.m_LocalSpacePoses
Vector3 [] Unity.MLAgents.Extensions.Sensors.PoseExtractor.m_ModelSpaceLinearVelocities
Vector3 [] Unity.MLAgents.Extensions.Sensors.PoseExtractor.m_LocalSpaceLinearVelocities
bool [] Unity.MLAgents.Extensions.Sensors.PoseExtractor.m_PoseEnabled
int Unity.MLAgents.Extensions.Sensors.PoseExtractor.NumEnabledPoses
Number of enabled poses in the hierarchy (read-only).
int Unity.MLAgents.Extensions.Sensors.PoseExtractor.NumPoses
Number of total poses in the hierarchy (read-only).
IEnumerable<Pose> Unity.MLAgents.Extensions.Sensors.PoseExtractor.GetEnabledModelSpacePoses()
Read iterator for the enabled model space transforms.
Referenced by Unity.MLAgents.Extensions.Sensors.ObservationWriterPhysicsExtensions.WritePoses.
IEnumerable<Pose> Unity.MLAgents.Extensions.Sensors.PoseExtractor.GetEnabledLocalSpacePoses()
Read iterator for the enabled local space transforms.
Referenced by Unity.MLAgents.Extensions.Sensors.ObservationWriterPhysicsExtensions.WritePoses.
IEnumerable<Vector3> Unity.MLAgents.Extensions.Sensors.PoseExtractor.GetEnabledModelSpaceVelocities()
Read iterator for the enabled model space linear velocities.
Referenced by Unity.MLAgents.Extensions.Sensors.ObservationWriterPhysicsExtensions.WritePoses.
IEnumerable<Vector3> Unity.MLAgents.Extensions.Sensors.PoseExtractor.GetEnabledLocalSpaceVelocities()
Read iterator for the enabled local space linear velocities.
Referenced by Unity.MLAgents.Extensions.Sensors.ObservationWriterPhysicsExtensions.WritePoses.
int Unity.MLAgents.Extensions.Sensors.PoseExtractor.GetParentIndex(int index)
Get the parent index of the body at the specified index.
index
void Unity.MLAgents.Extensions.Sensors.PoseExtractor.SetPoseEnabled(int index, bool val)
Set whether the pose at the given index is enabled or disabled for observations.
index val
bool Unity.MLAgents.Extensions.Sensors.PoseExtractor.IsPoseEnabled(int index)
void Unity.MLAgents.Extensions.Sensors.PoseExtractor.UpdateModelSpacePoses()
Update the internal model space transform storage based on the underlying system.
void Unity.MLAgents.Extensions.Sensors.PoseExtractor.UpdateLocalSpacePoses()
Update the internal model space transform storage based on the underlying system.
int Unity.MLAgents.Extensions.Sensors.PoseExtractor.GetNumPoseObservations(PhysicsSensorSettings settings)
Compute the number of floats needed to represent the poses for the given PhysicsSensorSettings.
settings
void Unity.MLAgents.Extensions.Sensors.PoseExtractor.Setup(int[] parentIndices)
Initialize with the mapping of parent indices. The 0th element is assumed to be -1, indicating that it's the root.
parentIndices
abstract Pose Unity.MLAgents.Extensions.Sensors.PoseExtractor.GetPoseAt(int index)
Return the world space Pose of the i'th object.
index
abstract Vector3 Unity.MLAgents.Extensions.Sensors.PoseExtractor.GetLinearVelocityAt(int index)
Return the world space linear velocity of the i'th object.
index
virtual Object Unity.MLAgents.Extensions.Sensors.PoseExtractor.GetObjectAt(int index)
Return the underlying object at the given index. This is only used for display in the inspector.
index
void Unity.MLAgents.Extensions.Sensors.PoseExtractor.DrawModelSpace(Vector3 offset)
IList<DisplayNode> Unity.MLAgents.Extensions.Sensors.PoseExtractor.GetDisplayNodes()
Get a list of display nodes in depth-first order.